[package]
name = "scrapfetch-rs"
version = "0.1.5"
edition = "2024"
license = "BSD3"
description = "Small system info splash"
homepage = "https://github.com/egevtech/scrapfetch-rs"
authors = ["Egevtech"]
readme = "README.md"
repository = "https://github.com/egevtech/scrapfetch-rs"

[dependencies]
strfmt = "0.2.5"
sysinfo = "0.37.2"
users = "0.11.0"

[package.metadata.generate-rpm]
assets = [
	{ source = "target/release/scrapfetch-rs", dest = "/usr/bin/scrapfetch-rs", mode = "755"}
]

[package.metadata.generate-rpm.requires]
which = "*"

[package.metadata.aur]
arch = ["any"]
makedepends = ["cargo", "rustup"]
depends = ["which"]
